import os
import re
import shutil
import zipfile
import argparse

def convert_to_wp(html_path, assets_path, theme_name):
    # 1. Read the HTML file
    try:
        with open(html_path, 'r', encoding='utf-8') as f:
            html = f.read()
    except FileNotFoundError:
        print(f"Error: Could not find HTML file at '{html_path}'")
        return

    # 2. Setup output directory
    theme_dir = theme_name
    os.makedirs(theme_dir, exist_ok=True)

    # 3. Extract CSS from <style> tags
    styles = re.findall(r'<style[^>]*>(.*?)</style>', html, flags=re.DOTALL | re.IGNORECASE)
    css_content = "\n".join(styles)
    # Remove large inline <style> tags to clean up the header
    html = re.sub(r'<style[^>]*>.*?</style>', '', html, flags=re.DOTALL | re.IGNORECASE)

    # 4. Fix asset paths (images, videos, etc.)
    html = re.sub(r'(src|href|data-mobile-video|data-desktop-video)=(["\'])/?assets/', 
                  r'\1=\2<?php echo get_template_directory_uri(); ?>/assets/', html)

    # 5. Split HTML into Header, Main, and Footer
    # Find the end of the <header> or <nav>
    header_end_match = re.search(r'</header>', html, flags=re.IGNORECASE)
    if not header_end_match:
        header_end_match = re.search(r'</nav>', html, flags=re.IGNORECASE)
    
    if header_end_match:
        header_end_idx = header_end_match.end()
    else:
        # Fallback to <main..., then </head>, then <body>, or default to 0
        main_start = re.search(r'<main', html, flags=re.IGNORECASE)
        if main_start:
            header_end_idx = main_start.start()
        else:
            head_end = re.search(r'</head>', html, flags=re.IGNORECASE)
            if head_end:
                header_end_idx = head_end.end()
            else:
                body_start = re.search(r'<body[^>]*>', html, flags=re.IGNORECASE)
                header_end_idx = body_start.end() if body_start else 0

    # Find the start of the <footer>
    footer_start_match = re.search(r'<footer', html, flags=re.IGNORECASE)
    if footer_start_match:
        footer_start_idx = footer_start_match.start()
    else:
        # Fallback to </body>, then end of document
        body_end = re.search(r'</body', html, flags=re.IGNORECASE)
        footer_start_idx = body_end.start() if body_end else len(html)

    header_html = html[:header_end_idx]
    main_html = html[header_end_idx:footer_start_idx]
    footer_html = html[footer_start_idx:]

    # Inject WordPress Hooks
    header_html = re.sub(r'</head>', r'<?php wp_head(); ?>\n</head>', header_html, flags=re.IGNORECASE)
    footer_html = re.sub(r'</body>', r'<?php wp_footer(); ?>\n</body>', footer_html, flags=re.IGNORECASE)

    # 6. Write PHP Files
    with open(os.path.join(theme_dir, 'header.php'), 'w', encoding='utf-8') as f:
        f.write(header_html)

    with open(os.path.join(theme_dir, 'footer.php'), 'w', encoding='utf-8') as f:
        f.write(footer_html)

    with open(os.path.join(theme_dir, 'front-page.php'), 'w', encoding='utf-8') as f:
        f.write("<?php get_header(); ?>\n" + main_html + "\n<?php get_footer(); ?>")

    with open(os.path.join(theme_dir, 'style.css'), 'w', encoding='utf-8') as f:
        f.write(f"/*\nTheme Name: {theme_name.replace('-', ' ').title()}\nDescription: Auto-generated by Antigravity Agent\nVersion: 1.0\n*/\n")
        f.write(css_content)

    with open(os.path.join(theme_dir, 'functions.php'), 'w', encoding='utf-8') as f:
        f.write("<?php\n")
        f.write("function auto_enqueue_scripts() {\n")
        f.write("    wp_enqueue_style('main-style', get_stylesheet_uri());\n")
        f.write("}\n")
        f.write("add_action('wp_enqueue_scripts', 'auto_enqueue_scripts');\n")
        f.write("add_theme_support('title-tag');\n")
        f.write("?>")

    # 7. Copy Assets folder
    if os.path.exists(assets_path):
        dest_assets = os.path.join(theme_dir, 'assets')
        if os.path.exists(dest_assets):
            shutil.rmtree(dest_assets)
        shutil.copytree(assets_path, dest_assets)
    else:
        print(f"Warning: Assets directory '{assets_path}' not found. Zip will be created without assets.")

    # 8. Zip the Theme
    zip_filename = f"{theme_name}.zip"
    with zipfile.ZipFile(zip_filename, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for root, dirs, files in os.walk(theme_dir):
            for file in files:
                file_path = os.path.join(root, file)
                arcname = os.path.relpath(file_path, os.path.dirname(theme_dir))
                zipf.write(file_path, arcname)
    
    # Cleanup unzipped folder to keep workspace clean
    shutil.rmtree(theme_dir)

    print(f"SUCCESS: Created {zip_filename}")

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Convert HTML to WP Theme")
    parser.add_argument('--html', required=True, help='Path to index.html')
    parser.add_argument('--assets', required=True, help='Path to assets directory')
    parser.add_argument('--theme', default='custom-theme', help='Name of the theme')
    args = parser.parse_args()
    
    convert_to_wp(args.html, args.assets, args.theme)