import os
import re
import shutil
import zipfile
import argparse

def clean_asset_path(path):
    path = path.strip()
    if path.startswith("./"):
        path = path[2:]
    return path

def replace_body_assets(text):
    text = re.sub(r'url\((["\']?)(?:\./)?assets/', r'url(\1<?php echo esc_url(get_template_directory_uri()); ?>/assets/', text)
    text = re.sub(r'(src|href|data-mobile-video|data-desktop-video|srcset)=(["\'])(?:\./)?assets/', r'\1=\2<?php echo esc_url(get_template_directory_uri()); ?>/assets/', text)
    
    def srcset_repl(m):
        val = m.group(2)
        val = re.sub(r'(?:\./)?assets/', r'<?php echo esc_url(get_template_directory_uri()); ?>/assets/', val)
        return f'srcset={m.group(1)}{val}{m.group(1)}'
    
    text = re.sub(r'srcset=(["\'])(.*?)\1', srcset_repl, text, flags=re.DOTALL)
    return text

def fix_header_assets(text):
    text = re.sub(r'(src|href|srcset)=(["\'])(?:\./)?(assets/[^"\']+)', r'\1=\2<?php echo esc_url(get_template_directory_uri()); ?>/\3', text)
    return text

def convert_to_wp(html_dir, assets_path, theme_name, single_html=None):
    theme_dir = theme_name
    os.makedirs(theme_dir, exist_ok=True)
    assets_dst = os.path.join(theme_dir, "assets")

    if single_html:
        files_to_process = {os.path.basename(single_html): {"template": "front-page.php", "name": "Front Page"}}
        base_html_path = single_html
    else:
        html_files = [f for f in os.listdir(html_dir) if f.endswith(".html")]
        if not html_files:
            print(f"Error: No HTML files found in '{html_dir}'")
            return
        
        files_to_process = {}
        if "index.html" in html_files:
            files_to_process["index.html"] = {"template": "front-page.php", "name": "Front Page"}
            base_html_path = os.path.join(html_dir, "index.html")
        else:
            first_file = sorted(html_files)[0]
            files_to_process[first_file] = {"template": "front-page.php", "name": "Front Page"}
            base_html_path = os.path.join(html_dir, first_file)

        for f in html_files:
            if f in files_to_process:
                continue
            slug = f.replace(".html", "")
            name = slug.replace("-", " ").title() + " Page"
            files_to_process[f] = {"template": f"template-{slug}.php", "name": name}

    try:
        with open(base_html_path, 'r', encoding='utf-8') as f:
            base_content = f.read()
    except FileNotFoundError:
        print(f"Error: Could not find base HTML file at '{base_html_path}'")
        return

    style_matches = re.findall(r'<style[^>]*>(.*?)</style>', base_content, flags=re.DOTALL | re.IGNORECASE)
    common_inline_css = "\n".join(style_matches)

    with open(os.path.join(theme_dir, 'style.css'), 'w', encoding='utf-8') as f:
        f.write(f"/*\nTheme Name: {theme_name.replace('-', ' ').title()}\nDescription: Auto-generated by Antigravity Agent\nVersion: 1.0\nText Domain: {theme_name}\n*/\n")
        f.write(common_inline_css)

    header_end = re.search(r'</header>', base_content, flags=re.IGNORECASE)
    if not header_end:
        header_end = re.search(r'</nav>', base_content, flags=re.IGNORECASE)
    
    if header_end:
        header_html = base_content[:header_end.end()]
    else:
        head_end_match = re.search(r'</head>', base_content, flags=re.IGNORECASE)
        header_html = base_content[:head_end_match.end()] if head_end_match else base_content

    header_html = re.sub(r'</head>', r'<?php wp_head(); ?>\n</head>', header_html, flags=re.IGNORECASE)
    header_html = re.sub(r'<title>.*?</title>', '', header_html, flags=re.IGNORECASE)
    header_html = re.sub(r'<meta name="description"[- =a-zA-Z0-9_"\'.]*?/>', '', header_html, flags=re.IGNORECASE)
    header_html = re.sub(r'<style[^>]*>.*?</style>', '', header_html, flags=re.DOTALL | re.IGNORECASE)
    header_html = re.sub(r'<link[^>]*href=["\']([^"\']*keen-slider\.min\.css[^"\']*)["\'][^>]*>', '', header_html, flags=re.IGNORECASE)

    header_html = re.sub(
        r'<header class=["\']main-header mobileTransparentMenu["\']>',
        '<header class="main-header <?php echo is_front_page() ? \'mobileTransparentMenu\' : \'\'; ?>">'.replace(r"\'", "'"),
        header_html,
        flags=re.IGNORECASE
    )
    header_html = re.sub(
        r'<g id="LEWIS-logo" class=["\']transition-all duration-1000 fill-white["\']>',
        '<g id="LEWIS-logo" class="transition-all duration-1000 <?php echo is_front_page() ? \'fill-white\' : \'fill-black md:fill-white\'; ?>">'.replace(r"\'", "'"),
        header_html,
        flags=re.IGNORECASE
    )

    header_html = header_html.replace('href="https://www.teamlewis.com/services/"', 'href="<?php echo esc_url(home_url(\'/services/\')); ?>"')
    header_html = header_html.replace('href="https://www.teamlewis.com/ai-technology-innovations/"', 'href="<?php echo esc_url(home_url(\'/ai/\')); ?>"')
    header_html = header_html.replace('href="https://www.teamlewis.com/case-studies/"', 'href="<?php echo esc_url(home_url(\'/case/\')); ?>"')
    header_html = header_html.replace('href="/magazine/"', 'href="<?php echo esc_url(home_url(\'/magazine/\')); ?>"')
    header_html = header_html.replace('href="https://www.teamlewis.com/contact/"', 'href="<?php echo esc_url(home_url(\'/contact/\')); ?>"')
    header_html = header_html.replace('href="https://www.teamlewis.com/agentic-search/"', 'href="<?php echo esc_url(home_url(\'/agentic-search/\')); ?>"')
    header_html = header_html.replace('href="https://www.teamlewis.com"', 'href="<?php echo esc_url(home_url(\'/\')); ?>"')

    header_html = fix_header_assets(header_html)
    with open(os.path.join(theme_dir, 'header.php'), 'w', encoding='utf-8') as f:
        f.write(header_html)

    footer_start = re.search(r'<footer', base_content, flags=re.IGNORECASE)
    if footer_start:
        footer_html = base_content[footer_start.start():]
    else:
        body_end_match = re.search(r'</body', base_content, flags=re.IGNORECASE)
        footer_html = base_content[body_end_match.start():] if body_end_match else "</body></html>"

    footer_html = re.sub(r'<script[^>]*>.*?</script>', '', footer_html, flags=re.DOTALL | re.IGNORECASE)
    footer_html = re.sub(r'</body>', r'<?php wp_footer(); ?>\n</body>', footer_html, flags=re.IGNORECASE)

    footer_html = footer_html.replace('href="https://www.teamlewis.com/services/"', 'href="<?php echo esc_url(home_url(\'/services/\')); ?>"')
    footer_html = footer_html.replace('href="https://www.teamlewis.com/ai-technology-innovations/"', 'href="<?php echo esc_url(home_url(\'/ai/\')); ?>"')
    footer_html = footer_html.replace('href="https://www.teamlewis.com/case-studies/"', 'href="<?php echo esc_url(home_url(\'/case/\')); ?>"')
    footer_html = footer_html.replace('href="/magazine/"', 'href="<?php echo esc_url(home_url(\'/magazine/\')); ?>"')
    footer_html = footer_html.replace('href="https://www.teamlewis.com/contact/"', 'href="<?php echo esc_url(home_url(\'/contact/\')); ?>"')
    footer_html = footer_html.replace('href="https://www.teamlewis.com/agentic-search/"', 'href="<?php echo esc_url(home_url(\'/agentic-search/\')); ?>"')
    footer_html = footer_html.replace('href="https://www.teamlewis.com"', 'href="<?php echo esc_url(home_url(\'/\')); ?>"')

    footer_html = fix_header_assets(footer_html)
    with open(os.path.join(theme_dir, 'footer.php'), 'w', encoding='utf-8') as f:
        f.write(footer_html)

    page_assets = {}
    for filename, page_info in files_to_process.items():
        filepath = single_html if single_html else os.path.join(html_dir, filename)
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()

        head_part = content[:content.find("</head>")] if "</head>" in content else ""
        css_links = re.findall(r'<link[^>]*href=["\']([^"\']*\.css[^"\']*)["\'][^>]*>', head_part, flags=re.IGNORECASE)
        js_scripts = re.findall(r'<script[^>]*src=["\']([^"\']*\.js[^"\']*)["\'][^>]*>', content, flags=re.IGNORECASE)

        css_cleaned = [clean_asset_path(c) for c in css_links if "assets/" in c or "foogallery" in c or "keen-slider" in c]
        js_cleaned = [clean_asset_path(j) for j in js_scripts if "assets/js" in j]

        page_assets[page_info["template"]] = {
            "css": css_cleaned,
            "js": js_cleaned
        }

        h_match = re.search(r'</header>', content, flags=re.IGNORECASE)
        h_idx = h_match.end() if h_match else 0
        f_match = re.search(r'<footer', content, flags=re.IGNORECASE)
        f_idx = f_match.start() if f_match else len(content)

        body_html = content[h_idx:f_idx]

        for script_path in js_cleaned:
            escaped_script = re.escape(script_path)
            body_html = re.sub(rf'<script[^>]*src=["\'](?:.*?){escaped_script}["\'][^>]*>.*?</script>', '', body_html, flags=re.DOTALL | re.IGNORECASE)

        body_html = replace_body_assets(body_html)

        body_html = body_html.replace('href="https://www.teamlewis.com/services/"', 'href="<?php echo esc_url(home_url(\'/services/\')); ?>"')
        body_html = body_html.replace('href="https://www.teamlewis.com/ai-technology-innovations/"', 'href="<?php echo esc_url(home_url(\'/ai/\')); ?>"')
        body_html = body_html.replace('href="https://www.teamlewis.com/case-studies/"', 'href="<?php echo esc_url(home_url(\'/case/\')); ?>"')
        body_html = body_html.replace('href="/magazine/"', 'href="<?php echo esc_url(home_url(\'/magazine/\')); ?>"')
        body_html = body_html.replace('href="https://www.teamlewis.com/contact/"', 'href="<?php echo esc_url(home_url(\'/contact/\')); ?>"')
        body_html = body_html.replace('href="https://www.teamlewis.com/agentic-search/"', 'href="<?php echo esc_url(home_url(\'/agentic-search/\')); ?>"')
        body_html = body_html.replace('href="https://www.teamlewis.com"', 'href="<?php echo esc_url(home_url(\'/\')); ?>"')

        template_filename = page_info["template"]
        with open(os.path.join(theme_dir, template_filename), 'w', encoding='utf-8') as out_f:
            if template_filename == "front-page.php":
                out_f.write("<?php get_header(); ?>\n" + body_html + "\n<?php get_footer(); ?>")
                # Also create index.php fallback template required by WordPress
                index_php_content = f"""<?php
/**
 * The main template file
 */
get_header();
?>
<main role="main" class="site-main">
    <div class="container mx-auto py-12 text-white">
        <?php
        if ( have_posts() ) :
            while ( have_posts() ) : the_post();
                ?>
                <article id="post-<?php the_ID(); ?>" <?php post_class('mb-8'); ?>>
                    <header class="entry-header mb-4">
                        <h1 class="entry-title text-3xl font-bold">
                            <a href="<?php the_permalink(); ?>" class="text-white"><?php the_title(); ?></a>
                        </h1>
                    </header>
                    <div class="entry-content">
                        <?php the_excerpt(); ?>
                    </div>
                </article>
                <?php
            endwhile;
            the_posts_navigation();
        else :
            ?>
            <p><?php esc_html_e( 'It seems we can&rsquo;t find what you&rsquo;re looking for.', '{theme_name}' ); ?></p>
            <?php
        endif;
        ?>
    </div>
</main>
<?php
get_footer();
"""
                with open(os.path.join(theme_dir, 'index.php'), 'w', encoding='utf-8') as idx_f:
                    idx_f.write(index_php_content)
            else:
                out_f.write(f"<?php\n/*\nTemplate Name: {page_info['name']}\n*/\nget_header();\n?>\n" + body_html + "\n<?php get_footer(); ?>")

    functions_php = f"""<?php
/**
 * {theme_name.replace('-', ' ').title()} Theme Functions
 */

function {theme_name.replace('-', '_')}_enqueue_assets() {{
    wp_enqueue_style('{theme_name}-style', get_stylesheet_uri(), array(), '1.0');
"""

    for template, assets in page_assets.items():
        if not assets["css"] and not assets["js"]:
            continue
        
        if template == "front-page.php":
            functions_php += "\n    if (is_front_page()) {\n"
        else:
            functions_php += f"\n    if (is_page_template('{template}')) {{\n"

        for css_path in assets["css"]:
            slug = os.path.basename(css_path).replace(".css", "").replace(".min", "")
            functions_php += f"        wp_enqueue_style('{theme_name}-{slug}', get_template_directory_uri() . '/{css_path}', array(), '1.0');\n"

        for js_path in assets["js"]:
            slug = os.path.basename(js_path).replace(".js", "").replace("-min", "").replace(".min", "").replace("_1", "-1")
            functions_php += f"        wp_enqueue_script('{theme_name}-{slug}', get_template_directory_uri() . '/{js_path}', array(), '1.0', true);\n"

        functions_php += "    }\n"

    functions_php += f"""
}}
add_action('wp_enqueue_scripts', '{theme_name.replace('-', '_')}_enqueue_assets');

add_action('after_setup_theme', '{theme_name.replace('-', '_')}_theme_supports');
function {theme_name.replace('-', '_')}_theme_supports() {{
    add_theme_support('title-tag');
    add_theme_support('post-thumbnails');
}}
?>"""

    with open(os.path.join(theme_dir, 'functions.php'), 'w', encoding='utf-8') as f:
        f.write(functions_php)

    if os.path.exists(assets_path):
        if os.path.exists(assets_dst):
            shutil.rmtree(assets_dst)
        shutil.copytree(assets_path, assets_dst)
        
        runtime_bundle_path = os.path.join(assets_dst, "js", "runtime.bundle.js")
        if os.path.exists(runtime_bundle_path):
            with open(runtime_bundle_path, "r", encoding="utf-8") as rf:
                js_content = rf.read()
            js_content = js_content.replace("/wp-content/themes/Lewis/static-homepage/dist/assets/", f"/wp-content/themes/{theme_name}/assets/")
            with open(runtime_bundle_path, "w", encoding="utf-8") as wf:
                wf.write(js_content)
    else:
        print(f"Warning: Assets directory '{assets_path}' not found.")

    zip_filename = f"{theme_name}.zip"
    with zipfile.ZipFile(zip_filename, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for root, dirs, files in os.walk(theme_dir):
            for file in files:
                file_path = os.path.join(root, file)
                arcname = os.path.relpath(file_path, os.path.dirname(theme_dir))
                zipf.write(file_path, arcname)
    
    shutil.rmtree(theme_dir)
    print(f"SUCCESS: Created {zip_filename}")

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Convert HTML to WP Theme")
    parser.add_argument('--html', help='Path to single index.html')
    parser.add_argument('--html-dir', help='Path to directory containing multiple HTML files')
    parser.add_argument('--assets', required=True, help='Path to assets directory')
    parser.add_argument('--theme', default='custom-theme', help='Name of the theme')
    args = parser.parse_args()
    
    if args.html_dir:
        convert_to_wp(html_dir=args.html_dir, assets_path=args.assets, theme_name=args.theme)
    elif args.html:
        convert_to_wp(html_dir=None, assets_path=args.assets, theme_name=args.theme, single_html=args.html)
    else:
        print("Error: You must provide either --html or --html-dir")